version: "3"

services:
  python_fastapi:
    image: anpr-api:1.0.0
    command:
      [
          "gunicorn", "-w", "5", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000", "--log-level=debug"
      ]
    environment:
      RUNTYPE: "cpu"
    ports:
      - 8000:8000