version: "3.9"

services:

  python_fastapi:
    container_name: anpr-api
    image: anpr:v1.1.6
    restart: always
    command:
      [
          "gunicorn", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000", "--log-level=debug"
      ]
    environment:
      RUNTYPE: "cpu"
      SAVE_DETECT: 1
      SAVE_NODETECT: 0
    ports:
      - 8000:8000
    volumes:
      - ./app/images:/code/app/images
